version: '3'

services:
  control_node:
    image: ubuntu:latest
    container_name: control_node
    volumes:
      - .:/ansible
    working_dir: /ansible
    command: /bin/bash -c "apt update && apt install -y ansible openssh-client && tail -f /dev/null"
    stdin_open: true
    tty: true

  target_node1:
    image: ubuntu:latest
    container_name: target_node1
    command: /bin/bash -c "apt update && apt install -y openssh-server && service ssh start && tail -f /dev/null"
    stdin_open: true
    tty: true

  target_node2:
    image: ubuntu:latest
    container_name: target_node2
    command: /bin/bash -c "apt update && apt install -y openssh-server && service ssh start && tail -f /dev/null"
    stdin_open: true
    tty: true
