- hosts: webserver
  become: yes
  tasks:
    - name: Install Apache
      package:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: present

    # - name: Enable Apache to start on boot
    #   service:
    #     name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    #     enabled: yes

    # - name: Start Apache
    #   service:
    #     name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
    #     state: started
