- hosts: webserver
  become: yes
  tasks:
    - name: Ensure Apache is installed
      package:
        name: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"
        state: present # Change state to absent if you want to uninstall
